### ISSUE TITLE
Integrity Issue?

### ISSUE THREAD

**Issue by Fl4sh9174** [KillzXGaming/Paper-Mario-Tools#1] opened 2024-05-28 05:30 UTC
So my feedback about the tool, it does the conversion and the repack just fine, but when i use the "new" file the game cant boot anymore, tried with a few different files and its not working, even if i just unpack/repack without changing a single parameter.

**Comment by KillzXGaming** [comment] 2024-05-29 19:33
Fixed now as of https://github.com/KillzXGaming/Paper-Mario-Tools/commit/f64cefa4191bf45ee1cc6f974aa7b4e07006e178 and is in release v1.1

**Closed as completed by KillzXGaming** 2024-05-29 19:33 UTC

**Comment by Fl4sh9174** [comment] 2024-05-30 20:25
Just letting you know, files modified with this tool are working fine on Yuzu, but crashing on ryujinx when the emulator try to access the repacked file.

**Comment by KillzXGaming** [comment] 2024-05-30 22:52
Are you sure the file is the cause of the crash, does it happen if the original file is there? Ryujinx just crashes in general for me so I am not sure what issues it has. I tested on my Switch and it seemed to have loaded fine.

**Comment by Fl4sh9174** [comment] 2024-05-31 01:10
Yes, im pretty sure its a ryujinx issue, but people think my mods are causing it, even its working on yuzu/switch, btw here the files original and modified, and after the repack they just crash on ryujinx, i can reproduce it anytime.

[Original.zip](https://github.com/user-attachments/files/15507183/Original.zip)
[Crashing.zip](https://github.com/user-attachments/files/15507184/Crashing.zip)

It happens when i try to access the west are of Rogueport, the emulator try to access this file and crash the emulator.

Its a part of the lighting fix im working on for this game, above 1080p the lighting issue get out of control, so i found a way to bypass it via exefs, but for some areas in specific i had to use this solution.

in case you need the mod to reproduce it:
[[Lighting Fix V2 1.0.0].zip](https://github.com/user-attachments/files/15507197/Lighting.Fix.V2.1.0.0.zip)
